# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_pay', models.IntegerField(default=0)),
                ('action', models.CharField(choices=[('Fashion and Lifestyle', 'Fashion and Lifestyle'), ('Sports, Politics and Education', 'Sports, Politics and Education'), ('Technology', 'Technology')], max_length=1)),
                ('tracking_ID', models.CharField(max_length=500)),
                ('activity_count', models.IntegerField(default=0)),
                ('decibel', models.FloatField(default=0.5)),
                ('preferences', models.CharField(choices=[('All', 'All'), ('Fashion and Lifestyle', 'Fashion and Lifestyle'), ('Sports, Politics and Education', 'Sports, Politics and Education'), ('Technology', 'Technology')], max_length=250)),
                ('budget', models.FloatField(default=0.0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Campaign',
                'ordering': ['campaign_id'],
            },
        ),
        migrations.CreateModel(
            name='NoisemakerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('twitter_handle', models.CharField(max_length=250)),
                ('facebook_handle', models.CharField(max_length=250)),
                ('instagram_handle', models.CharField(max_length=250)),
                ('twitter_ID', models.IntegerField(default=0)),
                ('facebook_ID', models.IntegerField(default=0)),
                ('instagram_ID', models.IntegerField(default=0)),
                ('number_of_friends', models.IntegerField(default=0)),
                ('escrow', models.FloatField(default=0.0)),
                ('decibel', models.FloatField(default=0.5)),
                ('account_number', models.IntegerField(default=0)),
                ('account_name', models.CharField(max_length=250)),
                ('bank_name', models.CharField(choices=[('Access Bank Plc', 'Access Bank Plc'), ('Diamond Bank Limited', 'Diamond Bank Limited'), ('Ecobank Nigeria Plc', 'Ecobank Nigeria Plc'), ('Fidelity Bank Plc', 'Fidelity Bank Plc'), ('First Bank of Nigeria Plc', 'First Bank of Nigeria Plc'), ('First City Monument Bank Ltd', 'First City Monument Bank Ltd'), ('Guaranty Trust Bank Plc', 'Guaranty Trust Bank Plc'), ('StanbicIBTC Bank', 'StanbicIBTC Bank'), ('Skye Bank', 'Skye Bank'), ('Standard Chartered Bank Nigeria Ltd', 'Standard Chartered Bank Nigeria Ltd'), ('Sterling Bank Plc', 'Sterling Bank Plc'), ('Union Bank of Nigeria Plc', 'Union Bank of Nigeria Plc'), ('United Bank for Africa Plc', 'United Bank for Africa Plc'), ('Unity Bank', 'Unity Bank'), ('Wema Bank Plc', 'Wema Bank Plc'), ('Zenith International Bank Ltd', 'Zenith International Bank Ltd')], max_length=1)),
                ('preferences', models.CharField(choices=[('Fashion and Lifestyle', 'Fashion and Lifestyle'), ('Sports, Politics and Education', 'Sports, Politics and Education'), ('Technology', 'Technology')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payouts',
            fields=[
                ('payout_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_requested', models.CharField(max_length=200)),
                ('approved', models.BooleanField()),
                ('note', models.TextField()),
                ('paid', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencers.NoisemakerProfile')),
            ],
            options={
                'db_table': 'Influencers Payment',
                'ordering': ['payout_id'],
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_ID', models.CharField(max_length=500)),
                ('action_count', models.CharField(max_length=10000)),
                ('tracked', models.BooleanField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencers.Campaigns')),
                ('trackers_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Activities',
            },
        ),
        migrations.AddField(
            model_name='campaigns',
            name='originator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
