# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigns',
            old_name='originator',
            new_name='user',
        ),
    ]
