# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-13 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_auto_20161107_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='action',
            field=models.CharField(choices=[('Fashion and Lifestyle', 'Fashion and Lifestyle'), ('Sports, Politics and Education', 'Sports, Politics and Education'), ('Technology', 'Technology')], max_length=100),
        ),
    ]
