# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_auto_20161114_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payouts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
