# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0008_auto_20161116_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
