# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0009_auto_20161116_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested', models.EmailField(max_length=254, unique=True, verbose_name='e-mail address')),
            ],
        ),
    ]
