# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0010_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='dummy_tracker',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigns',
            name='hash_tag',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigns',
            name='tweet',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='action',
            field=models.CharField(choices=[('Retweet', 'Retweet'), ('Follow', 'Follow'), ('Tweet', 'Tweet')], max_length=100),
        ),
    ]
