# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0013_auto_20161203_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='follow_handle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='hash_tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tweet',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
