# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0016_auto_20161203_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='dummy_tracker',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tracking_ID',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='tweet',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
