# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0017_auto_20161203_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouts',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
