# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0018_payouts_date_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='estimated_reach',
            field=models.IntegerField(default=0),
        ),
    ]
