# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0019_campaigns_estimated_reach'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
