# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0022_auto_20161205_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
