# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0023_campaigns_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noisemakerprofile',
            name='twitter_ID',
            field=models.BigIntegerField(default=0),
        ),
    ]
