# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0025_auto_20161212_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigns',
            options={'ordering': ['campaign_id'], 'verbose_name': 'Campaign'},
        ),
        migrations.AlterModelOptions(
            name='noisemakerprofile',
            options={'ordering': ['pk'], 'verbose_name': 'Noisemakerz Profile'},
        ),
        migrations.AlterModelOptions(
            name='payouts',
            options={'ordering': ['payout_id'], 'verbose_name': 'Noisemakerz Payout'},
        ),
        migrations.AlterModelOptions(
            name='requested',
            options={'verbose_name': 'Request'},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'verbose_name': 'Tracker'},
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='action',
            field=models.CharField(choices=[('Retweet', 'Retweet'), ('Follow', 'Follow'), ('Tweet', 'Tweet')], max_length=100, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='base_pay',
            field=models.IntegerField(default=0, verbose_name='base pay'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='budget',
            field=models.FloatField(default=0.0, verbose_name='budget'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='dummy_tracker',
            field=models.CharField(max_length=300, null=True, verbose_name='tracking number'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='preferences',
            field=models.CharField(choices=[('All', 'All'), ('Entertainment,Fashion,Lifestyle', 'Entertainment,Fashion,Lifestyle'), ('Internet,Technology,Computer & Software', 'Internet,Technology,Computer & Software'), ('Telecommunications,Publishing,News media', 'Telecommunications,Publishing,News media'), ('Health care,Food & Fruit,Agriculture', 'Health care,Food & Fruit,Agriculture'), ('Construction & Real Estate ,Hospitality & Travel', 'Construction & Real Estate ,Hospitality & Travel'), ('Women/Girl Advocacy', 'Women/Girl Advocacy'), ('Sports', 'Sports'), ('Defense & Arms,Public Administration,Politics', 'Defense & Arms,Public Administration,Politics'), ('Transportation Services,Automotive', 'Transportation Services,Automotive'), ('Financial services', 'Financial services'), ('Education', 'Education'), ('Aerospace', 'Aerospace')], max_length=250),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='noisemakerprofile',
            name='decibel',
            field=models.FloatField(default=0.5, verbose_name='decibel'),
        ),
        migrations.AlterField(
            model_name='noisemakerprofile',
            name='escrow',
            field=models.FloatField(default=0.0, verbose_name='account'),
        ),
        migrations.AlterField(
            model_name='noisemakerprofile',
            name='number_of_friends',
            field=models.IntegerField(default=0, verbose_name='number of friends'),
        ),
        migrations.AlterField(
            model_name='noisemakerprofile',
            name='preferences',
            field=models.CharField(choices=[('Entertainment,Fashion,Lifestyle', 'Entertainment,Fashion,Lifestyle'), ('Internet,Technology,Computer & Software', 'Internet,Technology,Computer & Software'), ('Telecommunications,Publishing,News media', 'Telecommunications,Publishing,News media'), ('Health care,Food & Fruit,Agriculture', 'Health care,Food & Fruit,Agriculture'), ('Construction & Real Estate ,Hospitality & Travel', 'Construction & Real Estate ,Hospitality & Travel'), ('Women/Girl Advocacy', 'Women/Girl Advocacy'), ('Sports', 'Sports'), ('Defense & Arms,Public Administration,Politics', 'Defense & Arms,Public Administration,Politics'), ('Transportation Services,Automotive', 'Transportation Services,Automotive'), ('Financial services', 'Financial services'), ('Education', 'Education'), ('Aerospace', 'Aerospace')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='noisemakerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='payouts',
            name='amount_requested',
            field=models.FloatField(default=0.0, verbose_name='amount requested'),
        ),
        migrations.AlterField(
            model_name='payouts',
            name='approved',
            field=models.BooleanField(verbose_name='approved'),
        ),
        migrations.AlterField(
            model_name='payouts',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date requested'),
        ),
        migrations.AlterField(
            model_name='payouts',
            name='note',
            field=models.TextField(verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='payouts',
            name='paid',
            field=models.BooleanField(verbose_name='paid'),
        ),
        migrations.AlterField(
            model_name='payouts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencers.Campaigns', verbose_name='campaign'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='trackers_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='tracking_ID',
            field=models.CharField(max_length=500, verbose_name='tracking id'),
        ),
    ]
