# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-16 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0026_auto_20161216_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='funded',
            field=models.BooleanField(default=False, verbose_name='funded'),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='influencers_budget',
            field=models.FloatField(default=0.0, verbose_name='influencers_budget'),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='lookup',
            field=models.SlugField(default=django.utils.crypto.get_random_string, max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='preferences',
            field=models.CharField(max_length=6500),
        ),
    ]
