# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0028_auto_20161220_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='lookup',
            field=models.SlugField(default=django.utils.crypto.get_random_string, max_length=13),
        ),
    ]
